export const BLOG_CHANGE_PAGE = 'BLOG_CHANGE_PAGE';
export const BLOG_CHANGE_IMAGE = 'BLOG_CHANGE_IMAGE';
export const BLOG_IMAGE_JUMP = 'BLOG_IMAGE_JUMP';
export const BLOG_SCROLL_TO_TOP = 'BLOG_SCROLL_TO_TOP';
export const BLOG_SCROLL_TO_BOTTOM = 'BLOG_SCROLL_TO_BOTTOM';
export const BLOG_CHANGE_TABS_MARGIN_TOP = 'BLOG_CHANGE_TABS_MARGIN_TOP';
export const BLOG_QUERY_POSTS = 'BLOG_QUERY_POSTS';
